# Site settings
title: Markus Weimer
email: website@weimo.de
description: "Building intelligent machines, one gradient at a time."
baseurl: "http://www.markusweimer.com"
url: "http://www.markusweimer.com"
twitter_username: markusweimer
github_username:  markusweimer

# Build settings
permalink: pretty
markdown: kramdown