# Site settings
title: Markus Weimer
email: website@weimo.de
description: "Building intelligent machines, one gradient at a time."
# baseurl: ""
url: "http://www.markusweimer.com"
twitter_username: markusweimer
github_username:  markusweimer

# Build settings
permalink: pretty

# Markdown settings for nice code formatting
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]