# Site settings
title: Markus Weimer
email: website@weimo.de
description: "Building intelligent machines, one gradient at a time."
# baseurl: ""
url: "http://www.markusweimer.com"
twitter_username: markusweimer
github_username:  markusweimer

# Build settings
markdown: kramdown
permalink: pretty
