# Site settings
title: Markus Weimer
email: website@weimo.de
description: "Building intelligent machines, one gradient at a time."
baseurl: ""
url: "https://www.weimo.de"
github_username:  markusweimer

# Build settings
permalink: pretty
markdown: kramdown